version: "3"
services:
  rt_messaging_app:
    build: .
    image: elleined/rt-messaging-api
    container_name: rt_messaging_app
    restart: always
    ports:
      - "8095:8095"
    environment:
      - MYSQL_HOST=mysql_server
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=rt_message_api_db
      - PORT=8095
    networks:
      - rt_messaging_network
    depends_on:
      mysql_server:
        condition: service_healthy
      redis_server:
        condition: service_healthy

  redis_server:
    image: 'redis:latest'
    container_name: redis_server
    ports:
      - '6379:6379'
    networks:
      - rt_messaging_network

  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rt_message_api_db
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"
    networks:
      - rt_messaging_network

networks:
  rt_messaging_network:
    name: rt_messaging_network
    ipam:
      driver: default
    external: false
