version: "3.8"
services:
  rt_messaging_app:
    image: elleined/rt-messaging-api:latest
    container_name: rt_messaging_app
    env_file:
      - .env
    ports:
      - "8095:8095"
    networks:
      - rt_messaging_network
    depends_on:
      mysql_server:
        condition: service_healthy
      redis_server:
        condition: service_healthy

  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6379:6379'
    networks:
      - rt_messaging_network

  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 300s
    networks:
      - rt_messaging_network

networks:
  rt_messaging_network:
    name: rt_messaging_network
    ipam:
      driver: default
    external: false
